# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

# Build settings
markdown: kramdown

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'bower.json']

rdf:
  subjects:
    - layout: "artist.html"
      query: |
        SELECT *
        WHERE {
          ?subject a <mo:MusicGroup>;
            <foaf:name> ?name.
        }
      url: "artists/{{ name | slugify }}.html"
    - layout: "event.html"
      query: |
        SELECT *
        WHERE {
          ?subject a <mo:Performance>;
            <dc:date> ?date;
            <mo:performer> ?performer.
          ?performer <foaf:name> ?performerName.
        }
      url: "events/{{ date }}-{{ performerName | slugify }}.html"
    - layout: "venue.html"
      query: |
        SELECT *
        WHERE {
          ?subject a <schema:Place>;
            <foaf:name> ?name.
        }
      url: "venues/{{ name | slugify }}.html"
